### ISSUE TITLE
Open the calendar on pop up

### ISSUE THREAD

**Issue by joaquinlom** [nodro7/angular-mydatepicker#1]
Hi.
thanks for keeping this fork of the kekeh repository.
I also was using the prev version, Right now I'm migrating the app to version 14 and the old module doesn't work.

I'm trying to use this one, but I'm not sure how to open the calendar in a pop up view and also keep the user to enter the date manually.

Thanks,

**Comment by nodro7** [comment]
Here's a basic example of an input that can accept a manual date along with a button to toggle the calendar...

```typescript
import { Component, ViewChild } from "@angular/core";
import {
  AngularMyDatePickerDirective,
  IAngularMyDpOptions,
} from "@nodro7/angular-mydatepicker";

@Component({
  selector: "app-root",
  template: `
    <input
      angular-mydatepicker
      #datePicker="angular-mydatepicker"
      placeholder="placeholder"
      autocomplete="off"
      [options]="myDatePickerOptions"
    />
    <button type="button" (click)="toggleCalendar()">
      Toggle
    </button>
  `,
  styles: [],
})
export class AppComponent {
  @ViewChild("datePicker") datePicker!: AngularMyDatePickerDirective;

  myDatePickerOptions: IAngularMyDpOptions = {
    appendSelectorToBody: true,
  };

  toggleCalendar(): void {
    this.datePicker.toggleCalendar();
  }
}
```

**Comment by joaquinlom** [comment]
Thanks. 
I didn't wanna keep tracking the styling of the general textbox and the calendar icon. I was able to use the old library with angular 14. so it keeps the same. Thank you

for reference: is the on I use - npm i mydatepicker@ng9

**Comment by nodro7** [comment]
No problem.

Just FYI, this repository is actually based on the newer version of Kekeh's datepicker - `angular-mydatepicker` not `mydatepicker` that you are using.
